
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppState() : Promise<AppState> {
    return await TAURI_INVOKE("get_app_state");
},
async initConfig(instanceUrl: string, syncDir: string, apiKey: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_config", { instanceUrl, syncDir, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAuth() : Promise<void> {
    await TAURI_INVOKE("start_auth");
},
/**
 * Start the background sync loop (idempotent: does nothing if already running).
 */
async startSync() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_sync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
authCompleteEvent: AuthCompleteEvent,
authErrorEvent: AuthErrorEvent,
syncStatusEvent: SyncStatusEvent
}>({
authCompleteEvent: "auth-complete-event",
authErrorEvent: "auth-error-event",
syncStatusEvent: "sync-status-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Application state returned by `get_app_state`.
 * 
 * **Frontend contract:** serializes as `"Unconfigured"` / `"Unauthenticated"` / `"Ready"` —
 * these string values are matched verbatim in `App.svelte`.
 */
export type AppState = "Unconfigured" | "Unauthenticated" | "Ready"
/**
 * Emitted when OAuth completes successfully.
 */
export type AuthCompleteEvent = null
/**
 * Emitted when OAuth fails.
 */
export type AuthErrorEvent = { message: string }
/**
 * Sync state reported via `sync_status` events.
 * 
 * **Frontend contract:** serializes as `"Syncing"` / `"Idle"` — matches
 * `Syncing.svelte` which checks `event.payload.status`.
 */
export type SyncState = "Syncing" | "Idle"
/**
 * Emitted each sync loop iteration.
 */
export type SyncStatusEvent = { status: SyncState; last_sync: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
